<?php

$data = json_encode([
    "amount"  => 100.0,
    "receiver"  => 50937007294,
    "desc" => 'Hello word'
]);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://sandbox.moncashbutton.digicelgroup.com/v1/Transfert');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJyZWFkLHdyaXRlIl0sImV4cCI6MTYzOTYxNzI1NCwianRpIjoiODE3YzZiMmItNzVlNy00NTE3LTgxYmEtOTUwMGJlMWI1NmUxIiwiY2xpZW50X2lkIjoiNjBjYWM5NzFhZDQxZTk5NzI0ZDJlMTFhODNlYWViZWMifQ.THIemrFkArmgejRf3tiejxgjlAcE-U6NiN_O-NsEHq1IqlTk8yJKI7rwIsU7lLOhdbzeLFcWRR7AbcIogDor3MxYT58sJWWOeMln-PfbiENc6MsVtJaM-o2s_KumXtDGV-_0s006wEkP5Xc8ggDJ0009S6dPk27vruRWTP4uaRBoxh2dWPiAG30rtCOaAwfHgQxNIEo-8CcIRbjjDsDwFt7R_cPqMybflzmLrOWUcya4AZDdXvBvonxrGdRFE75VkatrltNhFWdX3mtAkp8zM8SPOvb9nVWcI52jRUtZWS3N_RHthDj4bmYBSqQYyhbYreENhFvvCOsExHQ1kAoL6A';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$result = json_decode($result, true);

var_dump($result);
die();